<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Title");
?><?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("End User License Agreement");
?><div class="wrap contact_wrap">
	<div class="contacts_title">
		<? echo $APPLICATION->GetTitle() ?>
	</div>

	<h2>BASIC DEFINITIONS</h2>
<p>•	<b>Website visitors</b> — a person who came to the site https://mpozr.ru/ without the purpose of placing an Order.</p>
<p>•	<b>User</b> — is a natural person, a website visitor who accepts the terms of the present Agreement and wants to place Orders in the online store mpozr.ru.</p>
<p>•	<b>Buyer</b> — a consumer, a user who placed an Order in the online store mpozr.ru.</p>
<p>•	<b>Seller</b> — a limited liability company, OOO ZOLOTOE RUNO.</p>
<p>&nbsp;&nbsp;<b>Contacts:</b></br>
&nbsp;&nbsp;Actual address: 127238, the city of Moscow, Dmitrov highway, house 79, building 1, floor 2.</br>
&nbsp;&nbsp;E-mail: info@mpozr.ru.</br>
&nbsp;&nbsp;Telephone number: +7 (495) 744-79-12.</p>
<p>&nbsp;&nbsp;<b>Particulars:</b></br>
&nbsp;&nbsp;General director: Yarlykov Denis Viktorovich.</br>
&nbsp;&nbsp;Individual Taxpayer Number 7716804157 / OGRN code 1157746875736 / tax registration reason code 774301001.</br>
&nbsp;&nbsp;Registered office address: 127238, the city of Moscow, Dmitrov highway, house 79, building 1, room 5.</br>
&nbsp;&nbsp;Tel./ Fax: +7 (495) 744-79-12.</p>
<p>•	<b>Online store</b> — a website which is an aggregator of information about the Goods (services), owned by OOO ZOLOTOE RUNO and located on the Internet at mpozr.ru where the Goods offered by the Seller for purchase are presented, as well as the terms of payment and delivery of the Goods to Buyers.</p>
<p>•	<b>Aggregator of information about the goods (services)</b> — a website in the information and telecommunication network "Internet" mpozr.ru where the consumer is simultaneously presented with the opportunity to familiarize himself with the seller's proposal to conclude a sale and purchase agreement for the Goods and conclude a sale and purchase agreement with the seller for a certain product. The consumer is also given the opportunity to make a prepayment for the specified Goods by transferring funds to the owner of the aggregator (OOO ZOLOTOE RUNO) within the framework of the applied forms of cashless payments.</p>
<p>•	<b>Website</b> — https://mpozr.ru/.</p>
<p>•	<b>User account</b> – User / Buyer page, available after completing the registration procedure on the Website. The page contains personal data and access to it is carried out using a username and password. Actions performed through the User account are considered to have been committed by the User / Buyer, whose personal data are indicated in the User account.</p>
<p>•	<b>Goods</b> — headgears, clothing, accessories and other goods presented for sale on the Website.</p>
<p>•	<b>Order</b> — a duly completed request of the Buyer for the purchase and delivery of the Goods selected on the Site to the address specified by the Buyer / by picking up the Goods.</p>
<p>•	<b>Other manufacturers</b> — Partners of OOO ZOLOTOE RUNO, companies producing related products, included in the package to the products of OOO ZOLOTOE RUNO, or sold through the online store under partnership agreements.</p>

<h2>1. GENERAL PROVISIONS</h2>

<p><b>1.1</b> The Seller sells the Goods through the online store at https://mpozr.ru/.</p>
<p><b>1.2</b> By ordering the Goods through the online store, the User agrees to the terms of sale of the Goods stated below (hereinafter - the Terms of Sale of Goods). In case of disagreement with this User Agreement (hereinafter referred to as the Agreement / Public Offer), the User must immediately stop using the service and leave the website https://mpozr.ru/.</p>
<p><b>1.3</b> These Terms of Sale of Goods, as well as information about the Goods presented on the Site, are a public offer in accordance with Art. 435 and paragraph 2 of Art. 437 of the Civil Code of the Russian Federation.</p>
<p><b>1.4</b> The Agreement can be changed by OOO ZOLOTOE RUNO on a unilateral basis with notification by posting information on the Website. The new version of the Agreement shall enter into force on the following day from the date of its publication on the Site, unless otherwise provided by the terms of this Agreement.</p>
<p><b>1.5</b> The public offer is recognized as accepted by the Website Visitor / Buyer from the moment of registration by the Visitor on the Website, placing an Order by the Buyer without authorization on the Website as well as from the moment of acceptance of the Order from the Buyer by phone +7 (495) 744-79-12.</p>
<p><b>1.6</b> By informing OOO ZOLOTOE RUNO its e-mail and phone number, the Website Visitor / User / Buyer agrees to use of the specified communication means by OOO ZOLOTOE RUNO, as well as by the third parties involved by it for the purpose of fulfilling obligations to Website Visitors / Users / Buyers in order to deliver the goods, to transfer the order for delivery, as well as other information directly related to the fulfillment of the Buyer's obligations under this Public Offer.</p>
<p><b>1.7</b> By placing an Order, the User / Buyer agrees that the Seller can entrust the execution of the Agreement to a third party, while remaining responsible for its execution.</p>
<p><b>1.8</b> All rights and duties under the Agreement concluded with the User arise directly from the Seller and the Buyer, provided for by this Public Offer.</p>
<p><b>1.9</b> As part of the Order, OOO ZOLOTOE RUNO provides the User with information support of the Agreement concluded by the User with the Seller.</p>
<p><b>1.10</b> The buyer can place an order in the online store mpozr.ru on weekdays from 10:00 AM until 6:00 PM, except for periods of routine maintenance or technical failures.</p>
<p><b>1.11</b> The address and working hours of the Pick-up point through which it is possible to make a return: 127238, the city of Moscow, Dmitrov highway, house 79, building 1, floor 2, and on the Website in the "Contacts" section.</p>
<p><b>1.12</b> The provisions of the Law of the Russian Federation of 07.02.1992 N 2300-1 "On Protection of Consumer Rights" (hereinafter - the Law on Protection of Consumer Rights) are applied to the relationship between the Website Visitor / User / Buyer and the Seller, including the procedure for concluding and terminating a purchase and sale agreement consumer rights), the Rules for the sale of goods by remote means (Resolution of the Government of the Russian Federation of September 27, 2007 N 612), as well as the provisions of the Civil Code of the Russian Federation.</p>

<h2>2. SUBJECT OF THE AGREEMENT</h2>

<p><b>2.1</b> The subject of this Agreement is to enable the User to purchase the Goods presented in the catalog of the online store at https://mpozr.ru/., for personal, official and other needs not related to execution of entrepreneurial activities.</p>
<p><b>2.2</b> This Agreement applies to all types of Goods and services presented on the Site, as long as such offers with a description are presented in the catalog of the online store.</p>
<p><b>2.3</b> Retail Sales Agreement is considered to be made from the moment the Seller issues to the Buyer a cash or sales receipt or other document confirming payment for the Goods.</p>

<h2>3. REGISTRATION ON THE SITE</h2>

<p><b>3.1</b> Registration on the Site is carried out using the "Register" button.</p>
<p><b>3.2</b> Registration on the Site is not mandatory for ordering.</p>
<p><b>3.3</b> OOO ZOLOTOE RUNO is not responsible for the accuracy and correctness of the information provided by the User during registration.</p>
<p><b>3.4</b> The User undertakes not to disclose to the third parties the login and password specified by the User during registration. If the User has any suspicions about the security of his login and password or the possibility of their unauthorized use by the third parties, the User undertakes to immediately notify the Seller about this by sending an email to info@mpozr.ru.</p>
<p><b>3.5</b> Communication of the User / Buyer with the Call Center operators / managers and other representatives of the Seller should be based on the principles of common morality and communication etiquette. It is strictly forbidden to use obscene words, abuse, offensive language, as well as threats and blackmail, no matter in what form and to whom they were addressed.</p>

<h2>4. GOODS AND ORDER OF MAKING A PURCHASE</h2>

<p><b>4.1</b> In the absence of the Goods ordered by the Buyer in the Seller's warehouse, the latter is entitled to notify the Buyer about this by sending an appropriate e-mail to the address, indicated by the Buyer during registration or by calling of OOO ZOLOTOE RUNO Call Center operator, and offer alternative courses of action to such an Order, including cancellation.</p>
<p><b>4.2</b> In case of cancellation of a fully or partially prepaid Order, the cost of the canceled Goods is returned by the Seller to the Buyer in the manner in which the Goods were paid.</p>
<p><b>4.3</b> The Buyer's order is made in accordance with the procedures specified on the Website in the "For new users " section on https://mpozr.ru/dlia-novih-polzovateley/.</p>
<p><b>4.4</b> The Buyer is fully responsible for the provision of incorrect information, which incurred the impossibility of the Seller's proper performance of his obligations to the Buyer.</p>
<p><b>4.5</b> After placing the Order on the Website, the Buyer is provided with information about the estimated delivery date by sending an electronic message to the email address specified by the Buyer during registration or by phone. The representative of OOO ZOLOTOE RUNO serving this Order clarifies the details of the Order, the availability of the ordered Goods in the Seller's warehouse, agrees the delivery date and the time required for processing and delivery of the Order. The delivery date depends on the availability of the Goods ordered by the Buyer and on the region of delivery.</p>
<p><b>4.6</b> On the day of order delivery, the representative of OOO ZOLOTOE RUNO contacts the Buyer at the phone number contacts the Buyer at the phone number indicated at the time of ordering to agree on the exact delivery time within the Customer's interval as well as to obtain the necessary information from the Buyer to be able to pass (drive) to the address specified by the Buyer. In the event that the Buyer does not answer the call from the representative of OOO ZOLOTOYE RUNO the Seller has the right to postpone delivery to another time and (or) another day with the consent of the Buyer. In the event that the Buyer does not get in touch with the Seller and (or) does not agree on another time and (or) another day of delivery, the Seller's obligation to deliver the order is regarded to be fulfilled properly, and the Buyer is considered to have refused the order and fulfill the contract.</p>
<p><b>4.7</b> The expected date of transfer of the Order to the Delivery Service of the relevant Seller is communicated to the Buyer by serving the Order the representative of OOO ZOLOTOE RUNO, by e-mail or during a test call to the Buyer.</p>

<h2>5. DELIVERY OF THE ORDER</h2>

<p><b>5.1</b> Methods, as well as approximate delivery times for the Goods sold by OOO ZOLOTOE RUNO, information about the territory of delivery are indicated on the Site in the section "Delivery Methods" on https://mpozr.ru/dostavka/. Specific delivery dates can be agreed by the Buyer with the Call Center operator upon order confirmation. Transportation of the goods is carried out by a light vehicle.</p>
<p><b>5.2</b> The territory of delivery of the Goods presented on the Site is limited to the borders of the Russian Federation.</p>
<p><b>5.3</b> Upon delivery, the Order is handed over to the Buyer or to a third party specified in the Order as the recipient (hereinafter the Buyer and the third party are referred to as the "Recipient"). When it is not possible to receive the Order paid by bank transfer by the above-mentioned persons, the Order can be handed over to the person who can provide information about the Order (number of the delivery and / or full name of the Recipient).</p>
<p><b>5.4</b> To prevent fraud, as well as to fulfill the obligations assumed, the person delivering the Order has the right to request a document proving the identity of the Recipient, as well as indicate the type of document provided on the receipt for the Order upon delivery of the prepaid Order. The Seller guarantees the confidentiality and protection of the Recipient's personal data (Section 10).</p>
<p><b>5.5</b> The Recipient checks the Appearance and completeness of the Goods, as well as the completeness of the entire Order at the time of delivery of the Goods.</p>
<p><b>5.6</b> The cost of delivery for each Order is calculated individually, based on the weight of the Goods, the place and method of delivery, as well as (if necessary) the form of payment, and is indicated on the Website at the last stage of ordering. The cost of delivery depending on the delivery region is available at the link https://mpozr.ru/dostavka/.</p>
<p><b>5.7</b> The risk of accidental loss or accidental damage of the Goods is passed to the Buyer from the moment the Order is handed over to him and (or) affixed.</p>
<p><b>5.8</b> The obligation of the Seller to transfer the goods to the Buyer is considered fulfilled at the moment the deliveryman hands over the Goods to the Recipient or the Recipient receives the Goods at the post office or at the previously agreed place of issue of the Order (including Pick-up point). The Recipient of the order must sign the documents confirming the delivery of the Order. The seller is also considered to have fulfilled his obligations at the time of transfer of the Goods to the delivery service (carrier) or the organization of communication (Article 458 of the Civil Code of the Russian Federation).</p>
<p><b>5.9</b> Upon delivery of the Order by EMS courier service, the Recipient has the right to inspect the delivered Goods and open them in the presence of EMS employees after paying for the delivered Goods to check the Goods for compliance with the declared quantity, assortment and completeness of the Goods, as well as check the service life of the delivered Goods and the integrity of the packaging. In the case of any claims to the delivered Goods (shortage at delivery, attachment of the Goods other than the item specified in the inventory, manufacturing defects, other claims) upon the instructions of the Recipient, the EMS Service employees draw up an Act on the identified inconsistencies.</p>
<p><b>5.10</b> If the Goods delivered via the Russian Federation by the EMS courier service are returned due to claims against the Goods, the Recipient must attach the following documents to the shipment containing the returned Goods:</br>
- a signed application for refund;</br>
- a copy of the report on identified inconsistencies;</br>
- a copy of the payment receipt;</br>
- a copy of the Shipment inventory.</p>
<p><b>5.11</b> When accepting an Order from a delivery service employee, the Recipient has the right to inspect the delivered Goods and check it for compliance with the declared quantity, assortment and completeness of the Goods, as well as check the service life of the delivered Goods and the integrity of the packaging. In the absence of claims to the delivered Goods, the Recipient signs in the "Order delivery form" or another similar document provided by the delivery service employee. The signature in the delivery documents indicates that no claims to the Goods have been made by the Recipient and the Seller has fully and properly fulfilled his obligation to transfer the Goods.</p>
<p><b>5.12</b> The time spent by the representatives of OOO ZOLOTOE RUNO is limited to 15 minutes.</p>
<p><b>5.13</b> The Goods presented on the Website corresponds to National State Standard in terms of quality and packaging which is confirmed by the relevant documents (certificates, etc.).</p>
<p><b>5.14</b> The date and time can be checked with the representative of OOO ZOLOTOE RUNO who contacts the Buyer to confirm the Order. The Buyer accepts and agrees that the date and time of delivery of the Goods sold by Sellers other than OOO ZOLOTOE RUNO are in the exclusive competence of such Sellers; at the same time, employees and specialists of the Call-center undertake to provide any possible assistance and take measures in their control to provide the Buyer with such information.</p>
<p><b>5.15</b> In the event that the delivery of the Goods was made within the terms established by the contract, but the Goods were not transferred to the Buyer for reasons depending on the Buyer, the subsequent delivery is made on a new date agreed with the Seller, after the Buyer re-pays the cost of services for the delivery of the Goods (clause 24 the Rules for the sale of goods by remote means).</p>

<h2>6. PAYMENT FOR GOODS</h2>

<p><b>6.1</b> The price of the Goods sold in the online store is indicated in rubles of the Russian Federation and includes value added tax if the relevant Seller applies the general taxation system.</p>
<p><b>6.2</b> The price of the Goods is indicated on the Website. If the price for the Goods ordered by the Buyer is indicated / displayed incorrectly due to a technical failure, the Seller informs the Buyer about this so that to confirm the Order at the corrected price or to cancel the Order. If it is impossible to contact the Buyer, this Order is considered canceled. If the Order has been paid, the Seller returns to the Buyer the amount paid for the Order in the same way in which it was paid.</p>
<p><b>6.3</b> The price of the Goods on the Site can be changed by the Seller unilaterally. At the same time, the price for the Goods ordered by the Buyer cannot be changed. The price of the Goods may vary by region depending on economic indicators.</p>
<p><b>6.4</b> Features of payment for the Goods using bank cards:</br>
<b>6.4.1</b> In accordance with the regulation of the Central Bank of the Russian Federation "On the issue of bank cards and on transactions performed using payment cards" dated 24.12.2004 No. 266-P, transactions with bank cards are performed by the cardholder or his authorized person.</br>
<b>6.4.2</b> Authorization of transactions with bank cards is carried out by the bank. If the bank has reason to believe that the operation is fraudulent, then the bank has the right to refuse to carry out this operation. Fraudulent transactions with bank cards fall under Article 159 of the Criminal Code of the Russian Federation.</br>
<b>6.4.3</b> In order to avoid cases of various kinds of unlawful use of bank cards when paying, all Orders placed on the Website and prepaid with a bank card are checked by OOO ZOLOTOE RUNO. In order to verify the identity of the owner and his eligibility to use the card, OOO ZOLOTOE RUNO has the right to require the Buyer who has issued such an order to present an identity document.</p>
<p><b>6.5</b> OOO ZOLOTOE RUNO has the right to provide discounts on the Goods and establish a bonus program. The types of discounts, bonuses, the procedure and conditions for accrual are indicated on the Site and can be changed by OOO ZOLOTOE RUNO unilaterally (indicated on the Website https://mpozr.ru/skidki/).</p>
<p><b>6.6</b> If, when applying a discount / bonus, the recalculated cost of the Goods of OOO ZOLOTOE RUNO includes kopecks, such cost of the Goods shall be rounded down to a multiple of 1 (One) ruble.</p>
<p><b>6.7</b> When carrying out marketing activities involving the investment of any objects in shipments with the Buyer's Order, the delivery of these investments is carried out at the expense of the Buyer, which is indicated in the rules of the relevant marketing activities. In order to refuse an investment, the Buyer must contact the Customer Service (info@mpozr.ru).</p>
<p><b>6.8</b> When the goods OOO ZOLOTOE RUNO are delivered by EMS courier service, the total cost of the goods hall be increased by the cost of delivery in the amount specified in the Delivery Section (https://emspost.ru.com/tarify-ems).</p>
<p><b>6.9</b> The Order is considered incomplete if the Buyer reported a change in the purchase decision before the start of collecting the Order in the warehouse. If the Buyer informs the Seller about this after the start of assembling the Order in the warehouse, then such an Order is considered rejected.</p>
<p><b>6.10</b> The Company makes a decision on the application within 5 (five) business days after which it notifies the Buyer by sending a notification to the e-mail specified when submitting the application.</p>
<p>This indicted are not a manifestation of discrimination and are not aimed at infringing on the rights guaranteed by the legislation of the Russian Federation to consumers, but are aimed at reducing the losses of OOO ZOLOTOE RUNO from the actions of the Buyers..</p>

<h2>7.	RETURN OF GOODS AND MONEY</h2>

<p><b>7.1 GENERAL TERMS OF THE RETURN</b></p>
<p><b>7.1.1</b> The return of the Goods sold by OOO ZOLOTOE RUNO is carried out in accordance with the section "Return Conditions" indicated on the Site at https://mpozr.ru/vozvrat/. OOO ZOLOTOE RUNO is not responsible for the quality of the Goods sold by other Manufacturers.</p>
<p><b>7.1.2</b> To consider a return request you must send the Goods and a package of documents: a completed and printed application for a return (located in your personal account), a sales receipt to the address: 127238, the city of Moscow, Dmitrov highway, house 79, building 1, floor 2, OOO ZOLOTOE RUNO.</p>
<p><b>7.1.3</b> The current legislation does not provide for the Seller's obligation to go to the Buyer for the returned goods, except for the delivery of large-sized goods with defects and goods with defects weighing more than five kilograms for repair, discount, replacement and (or) their return to the Consumer.</p>
<p><b>7.1.4</b> Return methods:</br>
- In case of self-delivery to the address of location of OOO ZOLOTOE RUNO: 127238, the city of Moscow, Dmitrov highway, house 79, building 1, floor 2, the return of the Goods is free.</br>
- by EMS courier service: regardless of the method of receiving the order; the return of the Goods is paid.</p>
<p><b>7.1.5</b> The return is carried out on the basis of a completed application and the sales receipt confirming the fact and conditions of purchase. However, the absence of a sales receipt is not a reason for refusing to satisfy the claims.</p>
<p><b>7.1.6</b> When the buyer returns the goods, the consignment note or an act of return of the goods is drawn up. It indicates:</br>
<b>a)</b> the full brand name of the seller;</br>
<b>b)</b> the full name of the Buyer;</br>
<b>c)</b> the name of the Goods;</br>
<b>d)</b> the dates of the conclusion of the contract and transfer of goods;</br>
<b>e)</b> refundable amount of money;</br>
<b>f)</b> signature of the Seller and the Buyer (the Buyer’s representative).</br>
The refusal or evasion of the Seller from drawing up the act does not deprive the Buyer of the right to demand the return of the goods and (or) the return of the amount of money paid by the Buyer in accordance with the contract.</p>
<p><b>7.1.7</b> After quality control or examination of the Goods, it is returned to the Buyer by mail to the address specified by him/her in the return application.</p>
<p><b>7.2 RETURN OF GOODS OF PROPER QUALITY</b></p>
<p><b>7.2.1</b> The Buyer has the right to refuse the ordered Goods at any time before receiving it, and after receiving the Goods - within 14 days, not counting the day of purchase. The return of the Goods of proper quality is possible if its saleable condition (there are no traces of use and wear, the presence of original and undamaged packaging and labes), suitability.</p>
<p><b>7.2.2</b> If the Buyer refuses the Goods of proper quality, the Buyer must return the Goods to the Seller to check the safety of the saleable condition and suitability of the Goods. The refund paid by the Buyer to the Seller for the Goods occurs after the specified examination (part 4, article 26 of the Law "On Protection of Consumer Rights" and clarifications of Russian consumer protection agency Rospotrebnadzor of April 27, 2017).</p>
<p><b>7.2.3</b> If the Buyer refuses the Goods in accordance with clause 7.2.1., the Seller returns to him the cost of the returned Goods, with the exception of the Seller's expenses related to the delivery of the Goods returned by the Buyer (paragraph 21 of a decision by the Russian Government “On approval of the rules for the sale of the goods by remote means”), within 10 days from the date of receipt of the returned Goods at the Seller's warehouse along with the return application completed by the Buyer.</p>
<p><b>7.3 RETURN OF GOODS OF IMPROPER QUALITY</b></p>
<p><b>7.3.1</b> Goods of improper quality means a product that is defective and cannot ensure the performance of its functional qualities.</p>
<p><b>7.3.2</b> If the Goods of improper quality were handed over to the Buyer and the same was not previously agreed by the Seller, the Buyer has the right to use the provisions of Article 18 "Consumer rights upon detection of defects in the product" of the Law on the Protection of Consumer Rights.</p>
<p><b>7.3.3</b> The Seller is obliged to accept the goods of inadequate quality from the Buyer and, if necessary, to check the quality of the goods. The buyer is obliged to provide the goods for such verification (paragraphs 1 and 3 of the Article 18 of the Law of the Russian Federation "On Protection of Consumer Rights", Clarifications of the Federal Service for Supervision of Consumer Rights Protection and Human Wellbeing dated April 27, 2017, № 01/5278-17-29, Clarifications of Russian consumer protection agency Rospotrebnadzor of April 27, 2017).</p>
<p><b>7.3.4</b> In the event of a dispute about the reasons for the occurrence of defects in the Goods, the Seller is obliged to conduct an examination of the Goods at his/her own account. The examination of the Goods is carried out within 10 days from the date of the receipt of the Goods.</p>
<p><b>7.3.5</b> Требования о возврате уплаченной за Товар денежной суммы подлежат удовлетворению в течение 10 дней со дня предъявления соответствующего требования и возврата Товара Продавцу (ст. 22 Закона РФ «О защите прав потребителей», Разъяснение Роспотребнадзора от 27.04.2017 г.).</p>
<p><b>7.3.6</b> Refunds are made by returning the cost of the paid Goods to a bank card, by postal order or in cash in case of payment in cash. In the event of cancellation or return of the fully or partially prepaid Order, the value of the canceled order of the goods is returned by OOO ZOLOTOE RUNO to the Buyer in the same way in which the Goods were paid. The method must be indicated in the appropriate field of the application for the return of the Goods, which can be found at https://mpozr.ru/vozvrat/, or in another similar document issued by OOO ZOLOTOE RUNO.</p>
<p><b>7.3.7</b> When returning the Goods of improper quality, the Buyer has the right to demand compensation for the difference between the price of the corresponding Goods at the time of voluntary satisfaction of such a requirement, as well as compensation for confirmed postage costs.</p>

<h2>8. WARRANTY PERIOD</h2>

<p><b>8.1</b> The Buyer has the right to request the return of the Goods of improper quality at his choice to the manufacturer and the Seller within the warranty period.</p>
<p><b>8.2</b> The warranty period for clothes and shoes is 30 (thirty) calendar days from the date of purchase, unless otherwise established by the manufacturer of National State Standard. The warranty period established by the manufacturer is indicated in the description of the Goods. If the manufacturer’s warranty period is more than 30 (thirty) calendar days, then the manufacturer’s warranty period applies.</p>
<p><b>8.3</b> The warranty period for shoes starts from the moment of the corresponding season. The beginning of the season is determined by constituent entities of the Russian Federation based on the climatic conditions of the Buyer’s location (sub-paragraph 2, clause 2, article 19 of the Law of the Russian Federation "On Protection of Consumer Rights"). The beginning of the seasons in Moscow was established by the Government Decree of the City of Moscow dated July 16, 2013 N 466-pp “On establishing the timing of the onset of seasons for calculating the terms and service life of guaranteed goods in the city of Moscow”: the winter season lasts from November 1st to March 1st, the spring season lasts from March 1st to May 1st, the summer season lasts from May 1st to September 1st, autumn season lasts from September 1st to November 1st.</p>
<p><b>8.4</b> If the warranty period is established for the Goods, the Seller is responsible for the defects of the Goods in the event that he/she does not prove that these defects arose after the transfer of the Goods to the Buyer due to the Buyer’s violation of the application instructions, storage or transport regulations, actions of the third parties or irresistible nature.</p>
<p><b>8.5</b> If the warranty period is not established for the goods, the Buyer must prove that the defects of the Goods arose before the transfer of the Goods to the Buyer or for reasons that arose before that moment (clause 6, article 18 of the Law of the Russian Federation "On Protection of Consumer Rights").</p>
<p><b>8.6</b> If the warranty period is less than two years and the defects of the Goods are discovered after the expiration of the guarantee period, but within two years, the Buyer has the right to present claims to the Seller (manufacturer) if the Buyer proves that the defects of the Goods arose before its transfer to the consumer or for reasons that arose theretofore.</p>
<p><b>8.7</b> If a significant defect of the Goods is revealed after 2 years from the date of its transfer to the Buyer and the warranty period has expired by this time, the requirement to terminate the purchase and sale contract can be declared by the Buyer to the manufacturer only.  In this case, the Buyer is obliged to prove that the identified defect is significant and that it arose before the transfer of the Goods to the Buyer or for reasons that arose theretofore (clause 6, article 18 of the Law of the Russian Federation "On Protection of Consumer Rights", clause 7 of “Review of the practice of the court consideration of cases on disputes on the protection of consumer rights related to the sale of Goods and services” (affirmed by the Presidium of the Supreme Soviet dated October 17, 2018)).</p>

<h2>9. RESPONSIBILITY</h2>

<p><b>9.1</b> The Seller is not responsible for damage caused to the Buyer as a result of improper use of the Goods purchased in the online shop.</p>
<p><b>9.2 OOO ZOLOTOE RUNO is not responsible for the quality of the Goods produced by other Manufacturers (partner companies), as well as for their use of their obligations to transfer of Goods to the Buyer corresponding to the Order issued by the Buyer in terms of their completeness and quantity. By this presents the Buyer agrees that any claims regarding the quality, quantity and completeness of the Goods, as well as the delivery time of the Goods shall be sent to the Manufacturer whose Goods were ordered in the online store. OOO ZOLOTOE RUNO herewith undertakes to assist the Buyers in resolving their claims against the Sellers by providing all the information available to the OOO ZOLOTOE RUNO regarding the operating procedure, terms of sale and the return of the Goods, the location of the respective Manufacturers, as well as any other information essential for the resolution of such claims that are at the disposal of OOO ZOLOTOE RUNO and are not confidential by virtue of law or agreement.</b></p>
<p><b>9.3</b> The responsibility for the execution of the contract concluded by the Buyer with the Seller, as well as for the observance of consumer rights violated as a result of the transfer of the Goods of improper quality to the Buyer and the exchange of the Goods of proper quality for similar Goods, rests with the Seller.</p>
<p><b>9.4</b> The non-pecuniary damage caused to the Buyer as a result of violation by the Seller of consumer rights is eligible for compensation by the injurer if there is his/her fault.</p>

<h2>10. PRIVACY AND INFORMATION PROTECTION</h2>

<p><b>10.1</b> The personal data of the User / Buyer is processed in accordance with the Federal Law "On Personal Data" No. 152.</p>
<p><b>10.2</b> When registering on the Site, the User provides the following information: Last name, First name, Patronymic name, contact phone number, email address, date of birth, gender, delivery address of the goods.</p>
<p><b>10.3</b> By providing his/her personal data to the Seller, the Site Visitor / User / Buyer agrees to their processing by the Seller, as well as for fulfillment of the Seller's obligations to the Site Visitor / User / Buyer under this Public Offer, the Seller's promotion of goods and services, conducting electronic and sms surveys , monitoring the results of marketing campaigns, invitation to participate in ongoing programs to improve the quality of service, customer support, organizing the delivery of goods to Buyers, ensuring the process of returning the Goods from the Site Visitor / User / Buyer, processing a consumer loan from a partner company of the Seller, holding give-away among Site Visitors / Users / Buyers, monitoring the satisfaction of the Site Visitor / User / Buyer, as well as the quality of services provided by the Seller.</p>
<p><b>10.4</b> The processing of personal data means any action (operation) or a set of actions (operations) performed with personal data using automation tools or without using such tools, including collection, recording, systematization, accumulation, storage, clarification (update, change) extraction, use, transfer (including transfer to the third parties, not excluding cross-border transfer, if the need for it arose in the course of fulfilling obligations), depersonalization, blocking, deletion, destruction of personal data.</p>
<p><b>10.5</b> OOO ZOLOTOE RUNO has the right to send informational messages, including advertising messages, to the e-mail and mobile phone of the User / Buyer with his consent, expressed through the commission of actions that uniquely identify this subscriber and make it possible to reliable establish his/her will to receive a message. The User / Buyer has the right to refuse to receive advertising and other information without explaining the reasons for the refusal by informing OOO ZOLOTOE RUNO of your refusal by phone +7 (495) 744-79-12 or by sending a corresponding application to the email address OOO ZOLOTOE RUNO: info@mpozr.ru. Service messages informing the User / Buyer about the order and the stages of its processing are sent automatically and cannot be rejected by the User / Buyer.</p>
<p><b>10.6</b> Withdrawal of consent to the processing of personal data is carried out by withdrawal of acceptance of this Public Offer in the form specified here. For more details on the processing of personal data and on the procedure for exercising the rights provided by the Federal Law "On Personal Data" No. 152, see here.</p>
<p><b>10.7</b> OOO ZOLOTOE RUNO has the right to use the "cookies" technology. "Cookies" do not contain confidential information. The Site Visitor / User / Buyer hereby agrees to the collection, analysis and use of the "cookies", including by third parties for the purpose of generating statistics and optimizing advertising messages.</p>
<p><b>10.8</b> OOO ZOLOTOE RUNO receives information about the ip-address of the Website visitor https://mpozr.ru/. This information is not used to identify the visitor.</p>
<p><b>10.9</b> OOO ZOLOTOE RUNO is not responsible for the information provided by the User / Buyer on the Site in a public form.</p>
<p><b>10.10</b> OOO ZOLOTOE RUNO has the right to record telephone conversations with the User / Buyer, including to improve the quality of service. At the same time, OOO ZOLOTOE RUNO undertakes to prevent attempts of unauthorized access to information received during telephone conversations, and / or its transfer to the third parties not directly related to the execution of Orders, in accordance with paragraph 4 of Art. 16 of the Federal Law “On Information, Information Technologies and Information Protection”.</p>

<h2>11. VALIDITY OF THE PUBLIC OFFER</h2>

<p><b>11.1</b> This Public Offer comes into force from the moment it is accepted by the Site Visitor / Buyer, and is valid until the acceptance of the Public Offer is withdrawn or until its actual execution, whichever occurs first.</p>

<h2>12. ADDITIONAL TERMS AND CONDITIONS</h2>

<p><b>12.1</b> The Seller has the right to assign or in any other way transfer his rights and obligations arising from his relationship with the Buyer to the third parties.</p>
<p><b>12.2</b> The online shop and the services provided may be temporarily partially or completely unavailable due to maintenance or other work or for any other technical reasons. The technical service of OOO ZOLOTOE RUNO has the right to periodically carry out the necessary preventive or other work with or without prior notification to the Buyers.</p>
<p><b>12.3</b> The provisions of Russian legislation are applied to the relationship between the User / Buyer and the Seller.</p>
<p><b>12.4</b> In case of any questions and claims from the User / Buyer, he/she has the right to contact the Seller by phone or in any other available way specified in this Offer or the relevant section of the Site.</p>
<p><b>12.5</b> The recognition by the court of the invalidity of any provision of this Agreement does not entail the invalidity of the remaining provisions.</p>
<p><b>12.6</b> The Parties acknowledge that the Public Offer and response, various notices under the Agreement, including those related to the amendment and termination of the Agreement, signed with a simple electronic signature, are recognized as electronic documents equivalent to paper documents signed with a physical signature. A simple electronic signature is the Buyer's / Visitor's / User's email address specified when placing an Order.</p>

</div><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>